
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class DataMurid extends javax.swing.JFrame {

    /**
     * Creates new form DataMurid
     */
    public DataMurid() {
        initComponents();
        tampiltable();
        kosong();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrup_jk = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_idMurd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_namaMurd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Rb_lk = new javax.swing.JRadioButton();
        Rb_pr = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Cb_jrs = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmurid = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_updt = new javax.swing.JButton();
        txtcari1 = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA MURID");

        jLabel2.setText("ID");

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        btngrup_jk.add(Rb_lk);
        Rb_lk.setText("Laki-Laki");
        Rb_lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_lkActionPerformed(evt);
            }
        });

        btngrup_jk.add(Rb_pr);
        Rb_pr.setText("Perempuan");

        jLabel5.setText("Jurusan/Program");

        Cb_jrs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobile Programmer", "Network 1", "Network 2", "Network 3", "Software & Bussines", "Pariwisata", "AC", "Industri 4.0", "Design Grafis 1", "Design Grafis 2", "Motion Grafis" }));

        tabelmurid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelmurid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmuridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmurid);

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_updt.setText("Update");
        btn_updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updtActionPerformed(evt);
            }
        });

        txtcari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcari1ActionPerformed(evt);
            }
        });

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(Rb_pr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Rb_lk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_idMurd)
                                .addComponent(txt_namaMurd)
                                .addComponent(jLabel5)
                                .addComponent(Cb_jrs, 0, 200, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntambah)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_updt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtcari1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cari)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idMurd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_namaMurd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rb_lk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rb_pr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cb_jrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambah)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_updt)
                            .addComponent(jButton5))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rb_lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_lkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rb_lkActionPerformed

    
    private void txtcari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcari1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        HalamanUtama a = new HalamanUtama();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        
        //btn tambah ke database
         String rb_select = "";
        if(Rb_lk.isSelected()){
            rb_select = "L";
        }else{
            rb_select = "P";
        };
//        String Cb_set = "";
//        if(Cb_I.getSelectedIndex()== 0){
//            Cb_set = "Mobile Prigramming";
//        }else {
//            
//        }
        try{
            String Sql ="INSERT INTO murid VALUES ('"+txt_idMurd.getText()+"',"
                    + "'"+txt_namaMurd.getText()+"',"
                    + "'"+rb_select+"',"
                    + "'"+Cb_jrs.getSelectedItem()+"')";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan data");
            tampiltable();
            kosong();
            
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Gagal menambahkan");
            System.out.println(e);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        tampiltable();
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updtActionPerformed
        // TODO add your handling code here:
        String rb_select = "";
        if(Rb_lk.isSelected()){
            rb_select = "L";
        }else{
            rb_select = "P";
        };
//        String Cb_set = "";
//        if(Cb_I.getSelectedIndex()== 0){
//            Cb_set = "Mobile Prigramming";
//        }else {
//            
//        }
        try{
            String Sql ="UPDATE murid SET "
                    + "nama_murid = '"+txt_namaMurd.getText()+"',"
                    + "jenis_kelaminmrd = '"+rb_select+"',"
                    + "jurusan_program = '"+Cb_jrs.getSelectedItem()+"' WHERE id = '"+txt_idMurd.getText()+"' ";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan data");
            //kosong();
            tampiltable();
            kosong();
            
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Gagal menambahkan");
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_updtActionPerformed

    private void tabelmuridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmuridMouseClicked
        // TODO add your handling code here:
        int i = tabelmurid.rowAtPoint(evt.getPoint());
        txt_idMurd.setText(tabelmurid.getValueAt(i, 0).toString());
        txt_namaMurd.setText(tabelmurid.getValueAt(i, 1).toString());
        String JK = tabelmurid.getValueAt(i, 2).toString();
        if(JK.equals("L")){
            Rb_lk.setSelected(true);
        }else{
            Rb_pr.setSelected(true);
        }
        String Ka = tabelmurid.getValueAt(i, 3).toString();
        Cb_jrs.setSelectedItem(Ka);
    }//GEN-LAST:event_tabelmuridMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            String Sql ="DELETE FROM murid WHERE id = '"+txt_idMurd.getText()+"' ";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus data");
            kosong();
            tampiltable();
            
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Gagal menambahkan");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void kosong(){
        txt_idMurd.setText("");
        txt_namaMurd.setText("");
        Rb_lk.setSelected(false);
        Rb_pr.setSelected(false);
        
    }
    
    public void tampiltable(){
        DefaultTableModel tb = new DefaultTableModel();
        tabelmurid.setModel(tb);
        
        tb.addColumn("ID");
        tb.addColumn("Nama");
        tb.addColumn("Jenis Kelamin");
        tb.addColumn("Jurusan");
        
        
        try {
            String sql = "SELECT * FROM murid WHERE nama_murid LIKE '%"+txtcari1.getText()+"%' OR id = '"+txtcari1.getText()+"'";
            java.sql.Connection conn=(Connection)konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                tb.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            tabelmurid.setModel(tb);
        } catch (Exception e) {
        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMurid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMurid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMurid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMurid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMurid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_jrs;
    private javax.swing.JRadioButton Rb_lk;
    private javax.swing.JRadioButton Rb_pr;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_updt;
    private javax.swing.ButtonGroup btngrup_jk;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelmurid;
    private javax.swing.JTextField txt_idMurd;
    private javax.swing.JTextField txt_namaMurd;
    private javax.swing.JTextField txtcari1;
    // End of variables declaration//GEN-END:variables
}
