
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class DataKelas extends javax.swing.JFrame {

    /**
     * Creates new form DataKelas
     */
    public DataKelas() {
        initComponents();
        tampiltable();  
    }
    public void search(){
//        DefaultTableModel tb = new DefaultTableModel();
        
        
        DefaultTableModel tb = new DefaultTableModel();
//        tb.setRowCount(0);
        Kelas_tabel.setModel(tb);
        
        tb.addColumn("ID");
        tb.addColumn("Nama");
        tb.addColumn("Jenis Kelamin");
        tb.addColumn("Kelas");
        
        
        // memasukan data dari mysql
        try {
            String sql = "SELECT * FROM murid WHERE jurusan_program LIKE '%"+cb_aj.getSelectedItem()+"%'";
            java.sql.Connection conn=(Connection)konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                tb.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            Kelas_tabel.setModel(tb);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"gagal mencari");
        }
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        cb_jk = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama_w = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_wk = new javax.swing.JTable();
        btn_set = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        cb_aj = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Kelas_tabel = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_idwali = new javax.swing.JTextField();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobile Programmer", "Network 1", "Network 2", "Network 3", "Software & Bussines", "Pariwisata", "AC", "Industri 4.0", "Design Grafis 1", "Design Grafis 2", "Motion Grafis" }));

        jLabel1.setText("Kelas/Jurusan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Set Wali Kelas");

        jLabel3.setText("Nama Wali Kelas");

        table_wk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kelas", "Wali Kelas"
            }
        ));
        table_wk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_wkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_wk);

        btn_set.setText("Set");
        btn_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setActionPerformed(evt);
            }
        });

        btnup.setText("Update");
        btnup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupMouseClicked(evt);
            }
        });
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });

        cb_aj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobile Programmer", "Network 1", "Network 2", "Network 3", "Software & Bussines", "Pariwisata", "AC", "Industri 4.0", "Design Grafis 1", "Design Grafis 2", "Motion Grafis" }));

        jButton3.setText("Data Kelas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Kelas_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Jurusan", "Jenis Kelamin", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(Kelas_tabel);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Data Kelas");

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Id Wali Kelas");

        txt_idwali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idwaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_idwali, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_nama_w, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb_jk, javax.swing.GroupLayout.Alignment.LEADING, 0, 181, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cb_aj, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnup)
                                                    .addComponent(btn_set, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_idwali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nama_w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_set))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(btnup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_aj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        HalamanUtama a = new HalamanUtama();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupActionPerformed

    private void txt_idwaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idwaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idwaliActionPerformed

    private void btn_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setActionPerformed
        // TODO add your handling code here:
        //tambah ke data base
         String cb_select = "";
        if(cb_jk.getSelectedItem() == "Mobile Programmer"){
            cb_select = "MP";
        }else if(cb_jk.getSelectedItem() == "Network 1"){
            cb_select = "N1";
        }else if(cb_jk.getSelectedItem() == "Network 2"){
            cb_select = "N2";
        }else if(cb_jk.getSelectedItem() == "Network 3"){
            cb_select = "N3";
        }else if(cb_jk.getSelectedItem() == "Software & Bussines"){
            cb_select = "SB";
        }else if(cb_jk.getSelectedItem() == "Pariwisata"){
            cb_select = "PW";
        }else if(cb_jk.getSelectedItem() == "AC"){
            cb_select = "AC";
        }else if(cb_jk.getSelectedItem() == "Industri 4.0"){
            cb_select = "I4.0";
        }else if(cb_jk.getSelectedItem() == "Design Grafis 1"){
            cb_select = "DG1";
        }else if(cb_jk.getSelectedItem() == "Design Grafis 2"){
            cb_select = "DG2";
        }else{
            cb_select= "MG";
        }
//        String Cb_set = "";
//        if(Cb_I.getSelectedIndex()== 0){
//            Cb_set = "Mobile Prigramming";
//        }else {
//            
//        }
        try{
            String Sql ="INSERT INTO datawalikelas VALUES ('"+cb_select+"',"
                    + "'"+txt_idwali.getText()+"',"
                    + "'"+txt_nama_w.getText()+"',"
                    + "'"+cb_jk.getSelectedItem()+"')";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan data");
            
//            kosong();
            tampiltable();
            
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Gagal menambahkan");
            System.out.println(e);
        }                                     
    }//GEN-LAST:event_btn_setActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void table_wkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_wkMouseClicked
        // TODO add your handling code here:
        int i = table_wk.rowAtPoint(evt.getPoint());
        txt_idwali.setText(table_wk.getValueAt(i, 1).toString());
        txt_nama_w.setText(table_wk.getValueAt(i, 2).toString());
        
        String Ka = table_wk.getValueAt(i, 0).toString();
        if(Ka.equals("MP")){
            Ka = "Mobile Programmer";
        }else if(Ka.equals("N1")){
            Ka = "Network 1";
        }else if(Ka.equals("N2")){
            Ka = "Network 2";
        }else if(Ka.equals("N3")){
            Ka = "Network 3";
        }else if(Ka.equals("SB")){
            Ka = "Software & Bussines";
        }else if(Ka.equals("PW")){
            Ka = "Pariwisata";
        }else if(Ka.equals("AC")){
            Ka = "AC";
        }else if(Ka.equals("I4.0")){
            Ka = "Industri 4.0";
        }else if(Ka.equals("DG1")){
            Ka = "Design Grafis 1";
        }else if(Ka.equals("DG2")){
            Ka = "Design Grafis 2";
        }else if(Ka.equals("MG")){
            Ka= "Motion Grafis";
        }
        cb_jk.setSelectedItem(Ka);
    }//GEN-LAST:event_table_wkMouseClicked

    private void btnupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupMouseClicked
        // TODO add your handling code here:
         String cb_select = "";
        if(cb_jk.getSelectedItem() == "Mobile Programmer"){
            cb_select = "MP";
        }else if(cb_jk.getSelectedItem() == "Network 1"){
            cb_select = "N1";
        }else if(cb_jk.getSelectedItem() == "Network 2"){
            cb_select = "N2";
        }else if(cb_jk.getSelectedItem() == "Network 3"){
            cb_select = "N3";
        }else if(cb_jk.getSelectedItem() == "Software & Bussines"){
            cb_select = "SB";
        }else if(cb_jk.getSelectedItem() == "Pariwisata"){
            cb_select = "PW";
        }else if(cb_jk.getSelectedItem() == "AC"){
            cb_select = "AC";
        }else if(cb_jk.getSelectedItem() == "Industri 4.0"){
            cb_select = "I4.0";
        }else if(cb_jk.getSelectedItem() == "Design Grafis 1"){
            cb_select = "DG1";
        }else if(cb_jk.getSelectedItem() == "Design Grafis 2"){
            cb_select = "DG2";
        }else{
            cb_select= "MG";
        }
        try{
            String Sql ="UPDATE datawalikelas SET "
                    + "id_wk = '"+txt_idwali.getText()+"',"
                    + "nama_w = '"+txt_nama_w.getText()+"',"
                    + "kelas = '"+cb_jk.getSelectedItem()+"' WHERE id = '"+cb_select+"' ";
            java.sql.Connection conn =(Connection)konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan data");
            //kosong();
            tampiltable();
            
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Gagal menambahkan");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnupMouseClicked
     public void tampiltable(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("ID");
        tb.addColumn("ID Wali Kelas");
        tb.addColumn("Nama Wali Kelas");
        tb.addColumn("Kelas");
        
        
        
        // memasukan data dari mysql
        try {
            String sql = "select * from datawalikelas";
            java.sql.Connection conn=(Connection)konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                tb.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            table_wk.setModel(tb);
        } catch (Exception e) {
        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Kelas_tabel;
    private javax.swing.JButton btn_set;
    private javax.swing.JButton btnup;
    private javax.swing.JComboBox<String> cb_aj;
    private javax.swing.JComboBox<String> cb_jk;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_wk;
    private javax.swing.JTextField txt_idwali;
    private javax.swing.JTextField txt_nama_w;
    // End of variables declaration//GEN-END:variables
}
